# See : https://taskfile.dev/api/

version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I proto proto/sso/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
  generateMailer:
    aliases:
      - genmail
    desc: "Generate mailer from proto file"
    cmds:
      - protoc -I proto proto/mailer/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative